############# Portuguese navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "about/"
weight = 3

[[main]]
name = "Contato"
url = "contact/"
weight = 4

[[main]]
weight = 2
name = "Blog"
hasChildren = true

[[main]]
parent = "Blog"
name = "Posts"
url = "blog/"

[[main]]
parent = "Blog"
name = "Autores"
url = "authors/"

# footer menu
[[footer]]
name = "Sobre"
url = "about/"
weight = 1