############# Portuguese navigation ##############

main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "Blog"
    weight: 2
    hasChildren: true
  - name: "Curriculum"
    weight: 3
    hasChildren: true
  - name: "Sobre"
    url: "about/"
    weight: 4
  - name: "Contato"
    url: "contact/"
    weight: 5
  
  ### Blog children ###
  - parent: "Blog"
    name: "Posts"
    url: "blog/"
  - parent: "Blog"
    name: "Autores"
    url: "authors/"

  ### Curriculum children ###
  - parent: "Curriculum"
    name: "Ivan Álisson"
    url: "/"
  - parent: "Curriculum"
    name: "Gian Lucas"
    url: "/"
footer:
  - name: "Sobre"
    url: "about/"
    weight: 1
