############# Portuguese navigation ##############

main:
  - name: "Home"
    url: "/"
    weight: 1
  - name: "Blog"
    weight: 2
    hasChildren: true
  - name: "Sobre"
    url: "about/"
    weight: 3
  - name: "Contato"
    url: "contact/"
    weight: 4
  
  ### Blog children ###
  - parent: "Blog"
    name: "Posts"
    url: "blog/"
  - parent: "Blog"
    name: "Autores"
    url: "authors/"

footer:
  - name: "Sobre"
    url: "about/"
    weight: 1
