baseURL: 'https://example.org/'

## Theme
theme: 'ananke'
enableEmoji: true
enableMissingTranslationPlaceholders: true


## Config languages
### Global
defaultContentLanguage: "pt-br"
defaultContentLanguageInSubdir: true
params:
  contact:
    email: info@example.org
    phone: +55 10-999-888-777
title: IGLabs Dev

languages:
  pt-br:
    contentDir: content/pt-br
    disabled: false
    languageCode: pt-BR
    languageDirection: ltr
    languageName: Português
    weight: 1
    # params:
    #   color: blue
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    weight: 2
  es:
    contentDir: content/es
    disabled: true
    languageCode: es
    languageDirection: ltr
    languageName: Español
    weight: 3
  fr:
    contentDir: content/fr
    disabled: true
    languageCode: fr
    languageDirection: ltr
    languageName: Français
    weight: 4

